//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.CUSTOMER.APPLICATION.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRS.CUSTOMER.APPLICATION.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the store experience.
        /// </summary>
        public static string AboutTheStoreExperience {
            get {
                return ResourceManager.GetString("AboutTheStoreExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accompanying Fee.
        /// </summary>
        public static string Accompanying_Fee {
            get {
                return ResourceManager.GetString("Accompanying Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Logs.
        /// </summary>
        public static string ActivityLogs {
            get {
                return ResourceManager.GetString("ActivityLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Card.
        /// </summary>
        public static string Add_Card {
            get {
                return ResourceManager.GetString("Add Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Methods.
        /// </summary>
        public static string Add_Methods {
            get {
                return ResourceManager.GetString("Add Methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate Registration.
        /// </summary>
        public static string Affiliate_Registration {
            get {
                return ResourceManager.GetString("Affiliate Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required.
        /// </summary>
        public static string All_fields_are_required {
            get {
                return ResourceManager.GetString("All fields are required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string Allow {
            get {
                return ResourceManager.GetString("Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Location.
        /// </summary>
        public static string Allow_Location {
            get {
                return ResourceManager.GetString("Allow Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Payment Methods.
        /// </summary>
        public static string AllPaymentMethods {
            get {
                return ResourceManager.GetString("AllPaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Club Questionnaire.
        /// </summary>
        public static string AnswerClubQuestionnaire {
            get {
                return ResourceManager.GetString("AnswerClubQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the language.
        /// </summary>
        public static string Are_you_sure_you_want_to_change_the_language {
            get {
                return ResourceManager.GetString("Are you sure you want to change the language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Date.
        /// </summary>
        public static string ArrivalDate {
            get {
                return ResourceManager.GetString("ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Time.
        /// </summary>
        public static string ArrivalTime {
            get {
                return ResourceManager.GetString("ArrivalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Previous Page.
        /// </summary>
        public static string BackToPreviousPage {
            get {
                return ResourceManager.GetString("BackToPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        public static string Bank_Account {
            get {
                return ResourceManager.GetString("Bank Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Place.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Type.
        /// </summary>
        public static string Blood_Type {
            get {
                return ResourceManager.GetString("Blood Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        public static string Book_Now {
            get {
                return ResourceManager.GetString("Book Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking History.
        /// </summary>
        public static string BookingHistory {
            get {
                return ResourceManager.GetString("BookingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string Bookmark {
            get {
                return ResourceManager.GetString("Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        public static string BookNowSearch {
            get {
                return ResourceManager.GetString("BookNowSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book With This Plan.
        /// </summary>
        public static string BookWithThisPlan {
            get {
                return ResourceManager.GetString("BookWithThisPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Club Category.
        /// </summary>
        public static string By_Club_Category {
            get {
                return ResourceManager.GetString("By Club Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Previous Occupation.
        /// </summary>
        public static string By_Previous_Occupation {
            get {
                return ResourceManager.GetString("By Previous Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card holder&apos;s Name.
        /// </summary>
        public static string Card_holder_s_Name {
            get {
                return ResourceManager.GetString("Card holder s Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        public static string Card_number {
            get {
                return ResourceManager.GetString("Card number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Type.
        /// </summary>
        public static string Card_Type {
            get {
                return ResourceManager.GetString("Card Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Rank.
        /// </summary>
        public static string Choose_Rank {
            get {
                return ResourceManager.GetString("Choose Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from Location.
        /// </summary>
        public static string ChooseFromLocation {
            get {
                return ResourceManager.GetString("ChooseFromLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE YOUR FAVORITE HOST.
        /// </summary>
        public static string ChooseYourFavoriteHost {
            get {
                return ResourceManager.GetString("ChooseYourFavoriteHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        public static string Club {
            get {
                return ResourceManager.GetString("Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Details.
        /// </summary>
        public static string Club_Details {
            get {
                return ResourceManager.GetString("Club Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club recommended for you.
        /// </summary>
        public static string Club_recommended_for_you {
            get {
                return ResourceManager.GetString("Club recommended for you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Details.
        /// </summary>
        public static string ClubDetails {
            get {
                return ResourceManager.GetString("ClubDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Reservation.
        /// </summary>
        public static string ClubReservation {
            get {
                return ResourceManager.GetString("ClubReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club review.
        /// </summary>
        public static string ClubReview {
            get {
                return ResourceManager.GetString("ClubReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs.
        /// </summary>
        public static string Clubs {
            get {
                return ResourceManager.GetString("Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club Top.
        /// </summary>
        public static string ClubTop {
            get {
                return ResourceManager.GetString("ClubTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commented On.
        /// </summary>
        public static string Commented_On {
            get {
                return ResourceManager.GetString("Commented On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Review.
        /// </summary>
        public static string ConfirmReview {
            get {
                return ResourceManager.GetString("ConfirmReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the club you visited this time..
        /// </summary>
        public static string ConfirmTheClubYouVisitedThisTime {
            get {
                return ResourceManager.GetString("ConfirmTheClubYouVisitedThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the hosts that were in charge..
        /// </summary>
        public static string ConfirmTheHostsThatWereInCharge {
            get {
                return ResourceManager.GetString("ConfirmTheHostsThatWereInCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constellation.
        /// </summary>
        public static string Constellation {
            get {
                return ResourceManager.GetString("Constellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country/Region.
        /// </summary>
        public static string Country_Region {
            get {
                return ResourceManager.GetString("Country/Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cozy.
        /// </summary>
        public static string Cozy {
            get {
                return ResourceManager.GetString("Cozy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Password.
        /// </summary>
        public static string Create_New_Password {
            get {
                return ResourceManager.GetString("Create New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Password.
        /// </summary>
        public static string CreateNewPassword {
            get {
                return ResourceManager.GetString("CreateNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Linked.
        /// </summary>
        public static string Currently_Linked {
            get {
                return ResourceManager.GetString("Currently Linked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        public static string CustomerInformation {
            get {
                return ResourceManager.GetString("CustomerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV.
        /// </summary>
        public static string CVV {
            get {
                return ResourceManager.GetString("CVV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string Date_of_birth {
            get {
                return ResourceManager.GetString("Date of birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day By Day.
        /// </summary>
        public static string DayByDay {
            get {
                return ResourceManager.GetString("DayByDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string DeleteYourAccount {
            get {
                return ResourceManager.GetString("DeleteYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed information of club..
        /// </summary>
        public static string DetailedInformationOfClub {
            get {
                return ResourceManager.GetString("DetailedInformationOfClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn’t get a code?.
        /// </summary>
        public static string Did_not_get_a_code {
            get {
                return ResourceManager.GetString("Did not get a code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account ?.
        /// </summary>
        public static string Do_not_have_an_account {
            get {
                return ResourceManager.GetString("Do not have an account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need this information when saving a credit card?.
        /// </summary>
        public static string Do_you_need_this_information_when_saving_a_credit_card {
            get {
                return ResourceManager.GetString("Do you need this information when saving a credit card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink.
        /// </summary>
        public static string Drink {
            get {
                return ResourceManager.GetString("Drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 6 digit code sent in sms.
        /// </summary>
        public static string Enter_6_digit_code_sent_in_sms {
            get {
                return ResourceManager.GetString("Enter 6 digit code sent in sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter nickname.
        /// </summary>
        public static string Enter_nickname {
            get {
                return ResourceManager.GetString("Enter nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Phone Number.
        /// </summary>
        public static string Enter_Phone_Number {
            get {
                return ResourceManager.GetString("Enter Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluding Tax.
        /// </summary>
        public static string Excluding_Tax {
            get {
                return ResourceManager.GetString("Excluding Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience about club.
        /// </summary>
        public static string ExperienceAboutClub {
            get {
                return ResourceManager.GetString("ExperienceAboutClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string Expiry_Date {
            get {
                return ResourceManager.GetString("Expiry Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Course.
        /// </summary>
        public static string Extended_Course {
            get {
                return ResourceManager.GetString("Extended Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Host.
        /// </summary>
        public static string Find_a_Host {
            get {
                return ResourceManager.GetString("Find a Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Host Club.
        /// </summary>
        public static string FindAHostClub {
            get {
                return ResourceManager.GetString("FindAHostClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password?.
        /// </summary>
        public static string Forget_password {
            get {
                return ResourceManager.GetString("Forget password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Former Job.
        /// </summary>
        public static string Former_Job {
            get {
                return ResourceManager.GetString("Former Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Name.
        /// </summary>
        public static string GivenName {
            get {
                return ResourceManager.GetString("GivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back To Previous Page.
        /// </summary>
        public static string GoBackToPreviousPage {
            get {
                return ResourceManager.GetString("GoBackToPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoslog.
        /// </summary>
        public static string Hoslog {
            get {
                return ResourceManager.GetString("Hoslog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoslog Limited Plan.
        /// </summary>
        public static string Hoslog_Limited_Plan {
            get {
                return ResourceManager.GetString("Hoslog Limited Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoslog Limited Plan.
        /// </summary>
        public static string HoslogLimitedPlan {
            get {
                return ResourceManager.GetString("HoslogLimitedPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Blood Type.
        /// </summary>
        public static string Host_Blood_Type {
            get {
                return ResourceManager.GetString("Host Blood Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Constellation Group.
        /// </summary>
        public static string Host_Constellation_Group {
            get {
                return ResourceManager.GetString("Host Constellation Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Height.
        /// </summary>
        public static string Host_Height {
            get {
                return ResourceManager.GetString("Host Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host in charge.
        /// </summary>
        public static string Host_in_charge {
            get {
                return ResourceManager.GetString("Host in charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;assigned host&apos; is a user-selected option. Please note that the platform does not guarantee its authenticity from the operational side..
        /// </summary>
        public static string Host_in_charge_Info_Icon {
            get {
                return ResourceManager.GetString("Host_in_charge_Info_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Liquor Strength.
        /// </summary>
        public static string Host_Liquor_Strength {
            get {
                return ResourceManager.GetString("Host Liquor Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Ranking.
        /// </summary>
        public static string Host_Ranking {
            get {
                return ResourceManager.GetString("Host Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts recommended for you.
        /// </summary>
        public static string Host_Recommended_for_you {
            get {
                return ResourceManager.GetString("Host Recommended for you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to host clubs.
        /// </summary>
        public static string HostClubs {
            get {
                return ResourceManager.GetString("HostClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Detail.
        /// </summary>
        public static string HostDetail {
            get {
                return ResourceManager.GetString("HostDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour System.
        /// </summary>
        public static string HourSystem {
            get {
                return ResourceManager.GetString("HourSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Agree to Continue.
        /// </summary>
        public static string I_Agree_to_Continue {
            get {
                return ResourceManager.GetString("I Agree to Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (including tax).
        /// </summary>
        public static string IncludingTax {
            get {
                return ResourceManager.GetString("IncludingTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry.
        /// </summary>
        public static string Inquiry {
            get {
                return ResourceManager.GetString("Inquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string Invalid_Email {
            get {
                return ResourceManager.GetString("Invalid Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mobile number.
        /// </summary>
        public static string Invalid_mobile_number {
            get {
                return ResourceManager.GetString("Invalid_mobile_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this your first time using Hoslog?.
        /// </summary>
        public static string Is_this_your_first_time_using_Hoslog {
            get {
                return ResourceManager.GetString("Is this your first time using Hoslog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenshin.
        /// </summary>
        public static string Kenshin {
            get {
                return ResourceManager.GetString("Kenshin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langauge.
        /// </summary>
        public static string Langauge {
            get {
                return ResourceManager.GetString("Langauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Preference.
        /// </summary>
        public static string LanguagePreference {
            get {
                return ResourceManager.GetString("LanguagePreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Entry.
        /// </summary>
        public static string Last_Entry {
            get {
                return ResourceManager.GetString("Last Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Order.
        /// </summary>
        public static string Last_Order {
            get {
                return ResourceManager.GetString("Last Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Entry/ Last Order Time.
        /// </summary>
        public static string LastEntryLastOrderTime {
            get {
                return ResourceManager.GetString("LastEntryLastOrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should be 2 characters.
        /// </summary>
        public static string Length_should_be_2_characters {
            get {
                return ResourceManager.GetString("Length_should_be_2_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should be 4 characters.
        /// </summary>
        public static string Length_should_be_4_characters {
            get {
                return ResourceManager.GetString("Length_should_be_4_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of hosts.
        /// </summary>
        public static string ListOfHosts {
            get {
                return ResourceManager.GetString("ListOfHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with mobile.
        /// </summary>
        public static string Login_with_mobile {
            get {
                return ResourceManager.GetString("Login with mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobile number.
        /// </summary>
        public static string LoginPhoneNumber {
            get {
                return ResourceManager.GetString("LoginPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all as read.
        /// </summary>
        public static string Mark_all_as_read {
            get {
                return ResourceManager.GetString("Mark all as read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all as read.
        /// </summary>
        public static string MarkAllAsRead {
            get {
                return ResourceManager.GetString("MarkAllAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark This.
        /// </summary>
        public static string MarkThis {
            get {
                return ResourceManager.GetString("MarkThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length is 16 characters.
        /// </summary>
        public static string Maximum_length_is_16_characters {
            get {
                return ResourceManager.GetString("Maximum length is 16 characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length is 30 characters.
        /// </summary>
        public static string Maximum_length_is_30_characters {
            get {
                return ResourceManager.GetString("Maximum length is 30 characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length is 4 characters.
        /// </summary>
        public static string Maximum_length_is_4_characters {
            get {
                return ResourceManager.GetString("Maximum length is 4 characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Met handsome host.
        /// </summary>
        public static string Met_handsome_host {
            get {
                return ResourceManager.GetString("Met handsome host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimun length is 1 characters.
        /// </summary>
        public static string Minimum_length_is_1_characters {
            get {
                return ResourceManager.GetString("Minimum length is 1 characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length is 11 characters.
        /// </summary>
        public static string Minimum_length_is_11_characters {
            get {
                return ResourceManager.GetString("Minimum length is 11 characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimun length is 4 characters.
        /// </summary>
        public static string Minimum_length_is_4_characters {
            get {
                return ResourceManager.GetString("Minimum length is 4 characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length is 8 characters.
        /// </summary>
        public static string Minimum_length_is_8_characters {
            get {
                return ResourceManager.GetString("Minimum length is 8 characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your mobile number.
        /// </summary>
        public static string MobileNumberPlaceholder {
            get {
                return ResourceManager.GetString("MobileNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string MobileNumberRequired {
            get {
                return ResourceManager.GetString("MobileNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be atlest 8 characters.
        /// </summary>
        public static string MustBeAtlest8Characters {
            get {
                return ResourceManager.GetString("MustBeAtlest8Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVP.
        /// </summary>
        public static string MVP {
            get {
                return ResourceManager.GetString("MVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Hoslog Account.
        /// </summary>
        public static string New_Hoslog_Account {
            get {
                return ResourceManager.GetString("New Hoslog Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newly Added Club.
        /// </summary>
        public static string Newly_Added_Club {
            get {
                return ResourceManager.GetString("Newly Added Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomimation Fee.
        /// </summary>
        public static string Nomimation_Fee {
            get {
                return ResourceManager.GetString("Nomimation Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we couldn&apos;t find any matches. Try adjusting your search criteria..
        /// </summary>
        public static string NoSearchRecordFound {
            get {
                return ResourceManager.GetString("NoSearchRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of people.
        /// </summary>
        public static string NumberOfPeople {
            get {
                return ResourceManager.GetString("NumberOfPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older.
        /// </summary>
        public static string Older {
            get {
                return ResourceManager.GetString("Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-site Nomination.
        /// </summary>
        public static string On_site_Nomination {
            get {
                return ResourceManager.GetString("On-site Nomination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数字のみが許可されています.
        /// </summary>
        public static string Only_numbers_are_allowed {
            get {
                return ResourceManager.GetString("Only numbers are allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-site Nomination.
        /// </summary>
        public static string OnSiteNomination {
            get {
                return ResourceManager.GetString("OnSiteNomination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating Company.
        /// </summary>
        public static string OperatingCompany {
            get {
                return ResourceManager.GetString("OperatingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Club Gallery.
        /// </summary>
        public static string OverallClubGallery {
            get {
                return ResourceManager.GetString("OverallClubGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Experience about Club.
        /// </summary>
        public static string OverallExperienceAboutClub {
            get {
                return ResourceManager.GetString("OverallExperienceAboutClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must match.
        /// </summary>
        public static string Password_must_match {
            get {
                return ResourceManager.GetString("Password must match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must match.
        /// </summary>
        public static string PasswordMustMatch {
            get {
                return ResourceManager.GetString("PasswordMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Amount.
        /// </summary>
        public static string PaymentAmount {
            get {
                return ResourceManager.GetString("PaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Methods.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Options.
        /// </summary>
        public static string PaymentOptions {
            get {
                return ResourceManager.GetString("PaymentOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone no..
        /// </summary>
        public static string Phone_no {
            get {
                return ResourceManager.GetString("Phone no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number to login.
        /// </summary>
        public static string Phone_number_to_login {
            get {
                return ResourceManager.GetString("Phone number to login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick MVP.
        /// </summary>
        public static string PickMVP {
            get {
                return ResourceManager.GetString("PickMVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan B.
        /// </summary>
        public static string PlanB {
            get {
                return ResourceManager.GetString("PlanB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        public static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer a simple choice question..
        /// </summary>
        public static string PleaseAnswerASimpleChoiceQuestion {
            get {
                return ResourceManager.GetString("PleaseAnswerASimpleChoiceQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check The Review Content.
        /// </summary>
        public static string PleaseCheckTheReviewContent {
            get {
                return ResourceManager.GetString("PleaseCheckTheReviewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm the store you visited this time.
        /// </summary>
        public static string PleaseConfirmTheStoreYouVisitedThisTime {
            get {
                return ResourceManager.GetString("PleaseConfirmTheStoreYouVisitedThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give us your overall evaluation of the experience..
        /// </summary>
        public static string PleaseGiveUsYourOverallEvaluationOfTheExperience {
            get {
                return ResourceManager.GetString("PleaseGiveUsYourOverallEvaluationOfTheExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that the review is correct..
        /// </summary>
        public static string PleaseMakeSureThatTheReviewIsCorrect {
            get {
                return ResourceManager.GetString("PleaseMakeSureThatTheReviewIsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure there are no mistakes in the review target.
        /// </summary>
        public static string PleaseMakeSureThereAreNoMistakesInTheReviewTarget {
            get {
                return ResourceManager.GetString("PleaseMakeSureThereAreNoMistakesInTheReviewTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select all hosts you remember.
        /// </summary>
        public static string PleaseSelectAllHostsYouRemember {
            get {
                return ResourceManager.GetString("PleaseSelectAllHostsYouRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select all that apply to your experience.
        /// </summary>
        public static string PleaseSelectAllThatApplyToYourExperience {
            get {
                return ResourceManager.GetString("PleaseSelectAllThatApplyToYourExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select A Payment Method.
        /// </summary>
        public static string PleaseSelectAPaymentMethod {
            get {
                return ResourceManager.GetString("PleaseSelectAPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE SELECT A PLAN.
        /// </summary>
        public static string PleaseSelectAPlan {
            get {
                return ResourceManager.GetString("PleaseSelectAPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell us about your experience at the store..
        /// </summary>
        public static string PleaseTellUsAboutYourExperienceAtTheStore {
            get {
                return ResourceManager.GetString("PleaseTellUsAboutYourExperienceAtTheStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string Popularity {
            get {
                return ResourceManager.GetString("Popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post a review for this store.
        /// </summary>
        public static string PostAReviewForThisStore {
            get {
                return ResourceManager.GetString("PostAReviewForThisStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Host.
        /// </summary>
        public static string Preferred_Host {
            get {
                return ResourceManager.GetString("Preferred Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Location.
        /// </summary>
        public static string PreferredLocation {
            get {
                return ResourceManager.GetString("PreferredLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed To Next.
        /// </summary>
        public static string ProceedToNext {
            get {
                return ResourceManager.GetString("ProceedToNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Info.
        /// </summary>
        public static string ProfileInfo {
            get {
                return ResourceManager.GetString("ProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QnA about Club.
        /// </summary>
        public static string QnAAboutClub {
            get {
                return ResourceManager.GetString("QnAAboutClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate &amp; Review other host clubs.
        /// </summary>
        public static string Rate_ReviewOtherHostClubs {
            get {
                return ResourceManager.GetString("Rate&ReviewOtherHostClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate other host clubs.
        /// </summary>
        public static string RateOtherHostClubs {
            get {
                return ResourceManager.GetString("RateOtherHostClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-select the host.
        /// </summary>
        public static string Re_selectTheHost {
            get {
                return ResourceManager.GetString("Re-selectTheHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-select your host.
        /// </summary>
        public static string Re_SelectYourHost {
            get {
                return ResourceManager.GetString("Re-SelectYourHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Club.
        /// </summary>
        public static string RecommendedClub {
            get {
                return ResourceManager.GetString("RecommendedClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Hosts.
        /// </summary>
        public static string RecommendedHosts {
            get {
                return ResourceManager.GetString("RecommendedHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register an Account.
        /// </summary>
        public static string Register_an_Account {
            get {
                return ResourceManager.GetString("Register an Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Price.
        /// </summary>
        public static string Regular_Price {
            get {
                return ResourceManager.GetString("Regular Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a new code.
        /// </summary>
        public static string Request_a_new_code {
            get {
                return ResourceManager.GetString("Request a new code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservable.
        /// </summary>
        public static string Reservable {
            get {
                return ResourceManager.GetString("Reservable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Contents.
        /// </summary>
        public static string ReservationContents {
            get {
                return ResourceManager.GetString("ReservationContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Date.
        /// </summary>
        public static string ReservationDate {
            get {
                return ResourceManager.GetString("ReservationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation details.
        /// </summary>
        public static string ReservationDetails {
            get {
                return ResourceManager.GetString("ReservationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation History.
        /// </summary>
        public static string ReservationHistory {
            get {
                return ResourceManager.GetString("ReservationHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review &amp; Comments.
        /// </summary>
        public static string ReviewAndComments {
            get {
                return ResourceManager.GetString("ReviewAndComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Club.
        /// </summary>
        public static string ReviewClub {
            get {
                return ResourceManager.GetString("ReviewClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review what you think about the club?.
        /// </summary>
        public static string ReviewWhatYouThinkAboutTheClub {
            get {
                return ResourceManager.GetString("ReviewWhatYouThinkAboutTheClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rookie King Sales No.1.
        /// </summary>
        public static string RookieKingSalesNo1 {
            get {
                return ResourceManager.GetString("RookieKingSalesNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By.
        /// </summary>
        public static string Search_By {
            get {
                return ResourceManager.GetString("Search By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Handsomeness.
        /// </summary>
        public static string Search_by_Handsomeness {
            get {
                return ResourceManager.GetString("Search by Handsomeness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by nearest store.
        /// </summary>
        public static string Search_by_nearest_store {
            get {
                return ResourceManager.GetString("Search by nearest store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Filter.
        /// </summary>
        public static string Search_Filter {
            get {
                return ResourceManager.GetString("Search Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by store name, host name, or keyword.
        /// </summary>
        public static string Search_Filter_Placeholder {
            get {
                return ResourceManager.GetString("Search Filter Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string Search_Results {
            get {
                return ResourceManager.GetString("Search Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search from over.
        /// </summary>
        public static string SearchFromOver {
            get {
                return ResourceManager.GetString("SearchFromOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search host club.
        /// </summary>
        public static string SearchHostClub {
            get {
                return ResourceManager.GetString("SearchHostClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        public static string See_more {
            get {
                return ResourceManager.GetString("See more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string Select_Language {
            get {
                return ResourceManager.GetString("Select Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select according to your experience..
        /// </summary>
        public static string SelectAccordingToYourExperience {
            get {
                return ResourceManager.GetString("SelectAccordingToYourExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all the hosts you remember..
        /// </summary>
        public static string SelectAllTheHostsYouRemember {
            get {
                return ResourceManager.GetString("SelectAllTheHostsYouRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected host.
        /// </summary>
        public static string SelectedHost {
            get {
                return ResourceManager.GetString("SelectedHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Plan.
        /// </summary>
        public static string SelectedPlan {
            get {
                return ResourceManager.GetString("SelectedPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select multiple response about the overall club and host’s impressions..
        /// </summary>
        public static string SelectMultipleResponseAboutTheOverallClubAndHostsImpressions {
            get {
                return ResourceManager.GetString("SelectMultipleResponseAboutTheOverallClubAndHostsImpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up new password to login.
        /// </summary>
        public static string Set_up_a_new_password_to_login {
            get {
                return ResourceManager.GetString("Set up a new password to login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup new password to login.
        /// </summary>
        public static string SetupNewPasswordToLogin {
            get {
                return ResourceManager.GetString("SetupNewPasswordToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength of Alcohol.
        /// </summary>
        public static string Strength_of_Alcohol {
            get {
                return ResourceManager.GetString("Strength of Alcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stripe.
        /// </summary>
        public static string Stripe {
            get {
                return ResourceManager.GetString("Stripe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Including tax.
        /// </summary>
        public static string TaxIncluded {
            get {
                return ResourceManager.GetString("TaxIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us about your club experience..
        /// </summary>
        public static string TellUsAboutYourClubExperience {
            get {
                return ResourceManager.GetString("TellUsAboutYourClubExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use and Privacy Policy.
        /// </summary>
        public static string Terms_of_Use_and_Privacy_Policy {
            get {
                return ResourceManager.GetString("Terms of Use and Privacy Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your visit!.
        /// </summary>
        public static string Thank_you_for_your_visit_ {
            get {
                return ResourceManager.GetString("Thank you for your visit!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code will be sent through SMS.
        /// </summary>
        public static string The_code_will_be_sent_through_SMS {
            get {
                return ResourceManager.GetString("The code will be sent through SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of money for payment.
        /// </summary>
        public static string TheAmountOfMoneyForPayment {
            get {
                return ResourceManager.GetString("TheAmountOfMoneyForPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are seats available today.
        /// </summary>
        public static string There_are_seats_available_today {
            get {
                return ResourceManager.GetString("There are seats available today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected tag will be used as the title of the review..
        /// </summary>
        public static string TheSelectedTagWillBeUsedAsTheTitleOfTheReview {
            get {
                return ResourceManager.GetString("TheSelectedTagWillBeUsedAsTheTitleOfTheReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected tag will be used in the title of the review.
        /// </summary>
        public static string TheSelectedTagWillBeUsedInTheTitleOfTheReview {
            get {
                return ResourceManager.GetString("TheSelectedTagWillBeUsedInTheTitleOfTheReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string This_field_is_required {
            get {
                return ResourceManager.GetString("This_field_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag will be used for the review title.
        /// </summary>
        public static string ThisTagWillBeUsedForTheReviewTitle {
            get {
                return ResourceManager.GetString("ThisTagWillBeUsedForTheReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Time.
        /// </summary>
        public static string TimeChange {
            get {
                return ResourceManager.GetString("TimeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To confirm age.
        /// </summary>
        public static string ToConfirmAge {
            get {
                return ResourceManager.GetString("ToConfirmAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Reviews.
        /// </summary>
        public static string Top_Reviews {
            get {
                return ResourceManager.GetString("Top Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Page.
        /// </summary>
        public static string TopPage {
            get {
                return ResourceManager.GetString("TopPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Ranking.
        /// </summary>
        public static string TopRanking {
            get {
                return ResourceManager.GetString("TopRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreservable.
        /// </summary>
        public static string Unreservable {
            get {
                return ResourceManager.GetString("Unreservable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your profile.
        /// </summary>
        public static string UpdateYourProfile {
            get {
                return ResourceManager.GetString("UpdateYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up To Person.
        /// </summary>
        public static string UpToPerson {
            get {
                return ResourceManager.GetString("UpToPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Points.
        /// </summary>
        public static string UsedPoints {
            get {
                return ResourceManager.GetString("UsedPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide.
        /// </summary>
        public static string UserGuide {
            get {
                return ResourceManager.GetString("UserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Various Drinks.
        /// </summary>
        public static string Various_Drinks {
            get {
                return ResourceManager.GetString("Various Drinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited Date.
        /// </summary>
        public static string Visited_Date {
            get {
                return ResourceManager.GetString("Visited Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited On.
        /// </summary>
        public static string Visited_On {
            get {
                return ResourceManager.GetString("Visited On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site strictly prohibits viewing by anyone under the age of 18. Additionally, drinking alcohol for those under 20 years of age is prohibited by law..
        /// </summary>
        public static string WarningNotes {
            get {
                return ResourceManager.GetString("WarningNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will try to book your selected host..
        /// </summary>
        public static string WeWillTryToBookYourSelectedHost {
            get {
                return ResourceManager.GetString("WeWillTryToBookYourSelectedHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you most want to convey this time?.
        /// </summary>
        public static string WhatDoYouMostWantToConveyThisTime {
            get {
                return ResourceManager.GetString("WhatDoYouMostWantToConveyThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What I want to convey most.
        /// </summary>
        public static string WhatIWantToConveyMost {
            get {
                return ResourceManager.GetString("WhatIWantToConveyMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who was the most impressive host?.
        /// </summary>
        public static string WhoWasTheMostImpressiveHost {
            get {
                return ResourceManager.GetString("WhoWasTheMostImpressiveHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish to revisit.
        /// </summary>
        public static string Wish_to_revisit {
            get {
                return ResourceManager.GetString("Wish to revisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours.
        /// </summary>
        public static string Working_Hours {
            get {
                return ResourceManager.GetString("Working Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working hours &amp; Holiday.
        /// </summary>
        public static string WorkingHoursHoliday {
            get {
                return ResourceManager.GetString("WorkingHoursHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no Notifications yet..
        /// </summary>
        public static string You_have_no_Notifications_yet {
            get {
                return ResourceManager.GetString("You have no Notifications yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will earn 500 points.
        /// </summary>
        public static string You_will_earn_500_points {
            get {
                return ResourceManager.GetString("You will earn 500 points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can answer multiple answers about the overall atmosphere and impressions of the host..
        /// </summary>
        public static string YouCanAnswerMultipleAnswersAboutTheOverallAtmosphereAndImpressionsOfTheHost {
            get {
                return ResourceManager.GetString("YouCanAnswerMultipleAnswersAboutTheOverallAtmosphereAndImpressionsOfTheHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no notification yet..
        /// </summary>
        public static string YouHaveNoNotificationYet {
            get {
                return ResourceManager.GetString("YouHaveNoNotificationYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no Review &amp; Comments yet..
        /// </summary>
        public static string YouHaveNoReviewCommentsYet {
            get {
                return ResourceManager.GetString("YouHaveNoReviewCommentsYet", resourceCulture);
            }
        }
    }
}
